"""Two auxiliary soft-gated variants kept for in-text claims: the MF meta-controller
and the with-replacement sampler (both patched exactly like softgate_model_comparison)."""
import warnings; warnings.filterwarnings('ignore')
import os, time
import pandas as pd
from recovery_em import em_fit
import mfit_softgate_gen as LK   # generated by softgate_model_comparison.py

G, B, N = 'gamma', 'beta', 'norm'
_MBbd = [['MB_B', G, [1, 1]], ['MB_depth', B, [1, 1]], ['MB_breadth', B, [1, 1]],
         ['breadth2', B, [1, 1]]]
_MBcrfcb = _MBbd + [['mbcache', G, [1, 1]], ['CB', N, [0, 5]], ['forgetC', G, [1, 1]],
                    ['cache_reward', N, [0, 5]]]
EXTRAS = [
    ('MBMC_MF',      LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting_MF, _MBcrfcb),
    ('MBMC_replace', LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting_replacement_execution,
                     _MBcrfcb + [['cache_plan', G, [1, 1]]]),
]
d = pd.read_csv('lmm_fixed.csv')
dfs = [d[d['sub'] == s].reset_index(drop=True) for s in d['sub'].unique()]
rows = []
for name, lik, pinfo in EXTRAS:
    t0 = time.time()
    ibic, _r, _f = em_fit(dfs, [list(p) for p in pinfo], lik, sample_size=10000,
                          cores=max(1, (os.cpu_count() or 8) - 2), max_iter=30,
                          verbose=False, seed0=1)
    rows.append(dict(model=name, k=len(pinfo), iBIC=round(ibic, 2)))
    print(f'{name:14s} k={len(pinfo)}  iBIC={ibic:.2f}  ({time.time()-t0:.0f}s)', flush=True)
pd.DataFrame(rows).to_csv('softgate_extra_variants_BICs.csv', index=False)
print('EXTRAS DONE', flush=True)
