"""
Relinquish-value model-class variant, fit to Study 2 real data.

Variant: when only a ONE-STEP plan is known (one_ok) -- the agent knows which single
action keeps the goal attainable -- relinquishing is worth
    v_rel = 0.5*(R+1) + 0.5*1  =  1 + 0.5*R,      R = 4*discount**(3-decision)
(the computer picks the known-good action half the time) instead of v_rel = 1.
The two-step (v_rel = 1+R) and fail (v_rel = 1) branches are unchanged.

The variant likelihood class is generated by source-patching mfit_likelihoods.py
(every MB* likelihood's one-step branch), written to mfit_likelihoods_relhalf.py.
All 13 models of the study-2 class (model_recovery_em.CANDIDATES) are then fit to
study2/lmm_fixed.csv with the SAME hierarchical EM / iterative importance sampling
as model_fitting.py (recovery_em.em_fit; iBIC = -2*evidence + 2k*ln(N*60)).
Cache-only models (CB, CCRF, CCRF_CB) have no planning values -> variant == original
(fit once, reported in both columns).
"""
import os
import re
import sys
import time
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, '..', 'study2'))

import recovery_common as rc          # noqa: E402  (process_subject)
from recovery_em import em_fit        # noqa: E402
import mfit_likelihoods as LK         # noqa: E402

# 13-model class, verbatim from model_recovery_em.CANDIDATES (inlined because that
# module imports the unavailable `cbm` package at top level).
G, B, N = 'gamma', 'beta', 'norm'
_MBB = [['MB_B', G, [1, 1]]]
_MB2 = _MBB + [['MB_depth', B, [1, 1]]]
_MBbd = _MBB + [['MB_depth', B, [1, 1]], ['MB_breadth', B, [1, 1]], ['breadth2', B, [1, 1]]]
_MBc = _MBbd + [['mbcache', G, [1, 1]]]
_MBcr = _MBc + [['cache_reward', N, [0, 5]]]
_MBcrf = _MBcr + [['forget', G, [1, 1]]]
_MBcrfcb = _MBbd + [['mbcache', G, [1, 1]], ['CB', N, [0, 5]], ['forgetC', G, [1, 1]],
                    ['cache_reward', N, [0, 5]]]
CANDIDATES = [
    ('CB',            LK.CacheR_CB_1, [['CB', N, [0, 5]]]),
    ('CCRF',          LK.CacheR_CB_3, [['mbcache', G, [1, 1]], ['forgetC', G, [1, 1]],
                                       ['cache_reward', N, [0, 5]]]),
    ('CCRF_CB',       LK.CacheR_CB_4, [['CB', N, [0, 5]], ['mbcache', G, [1, 1]],
                                       ['forgetC', G, [1, 1]], ['cache_reward', N, [0, 5]]]),
    ('MBMC_optimal',  LK.MB_actionSeparation, _MBB),
    ('MBMC_Depth',    LK.MB_Depth_actionSeparation, _MB2),
    ('MBMC_Breadth2', LK.MB_Breadth_actionSeparation,
                      _MBB + [['MB_breadth', B, [1, 1]], ['breadth2', B, [1, 1]]]),
    ('MBMC_Breadth1', LK.MB_oneBreadth_Depth_actionSeparation,
                      _MBB + [['MB_depth', B, [1, 1]], ['MB_breadth', B, [1, 1]]]),
    ('MBMC_BD',       LK.MB_Breadth_Depth_actionSeparation, _MBbd),
    ('MBMC_CC',       LK.MB_Breadth_Depth_actionSeparation_MBcache1_fullmemory, _MBc),
    ('MBMC_CCR',      LK.MB_Breadth_Depth_actionSeparation_MBcache2_fullmemory, _MBcr),
    ('MBMC_CCRF',     LK.MB_Breadth_Depth_actionSeparation_MBcache2_limitedmemory, _MBcrf),
    ('MBMC_CCRF_CB',  LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting, _MBcrfcb),
    ('MBMC_full',     LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting_execution,
                      _MBcrfcb + [['cache_plan', G, [1, 1]]]),
]

SS = 10000
CORES = max(1, (os.cpu_count() or 8) - 2)
MAXITER = 30
SEED0 = 7
CACHE_ONLY = {'CB', 'CCRF', 'CCRF_CB'}   # no planning values -> unaffected

VARIANT_PATH = os.path.join(HERE, 'mfit_likelihoods_relhalf.py')
PATCH_RE = re.compile(r'v1_rel\s*\+=\s*1\b')
PATCH_TO = 'v1_rel += 1 + 0.5*4*(discount_rate**(3-decision))'


def build_variant_module():
    src = open(os.path.join(HERE, 'mfit_likelihoods.py')).read()
    patched, n = PATCH_RE.subn(PATCH_TO, src)
    header = ('# AUTO-GENERATED from mfit_likelihoods.py by fit_relinquish_variant.py\n'
              '# one-step-success relinquish value: 1 -> 1 + 0.5*R (R = 4*disc**(3-d))\n')
    open(VARIANT_PATH, 'w').write(header + patched)
    print(f'variant module written: {n} one-step v1_rel branches patched')
    assert n >= 5 * 16, f'expected >=80 patches, got {n}'
    import importlib
    import mfit_likelihoods_relhalf as LKV
    importlib.reload(LKV)
    return LKV


def load_study2():
    d = pd.read_csv(os.path.join(HERE, '..', 'study2', 'lmm_fixed.csv'))
    subs = d['sub'].unique()
    dfs = [d[d['sub'] == s].reset_index(drop=True) for s in subs]
    print(f'study2: {len(dfs)} subjects loaded')
    return dfs


def fit_one(dfs, lik, pinfo, tag):
    t0 = time.time()
    ibic, _res, _fit = em_fit(dfs, pinfo, lik, sample_size=SS, cores=CORES,
                              max_iter=MAXITER, verbose=False, seed0=SEED0)
    print(f'    {tag}: iBIC={ibic:.1f}  ({time.time()-t0:.0f}s)', flush=True)
    return ibic


def main():
    LKV = build_variant_module()
    dfs = load_study2()
    rows = []
    for label, lik, pinfo in CANDIDATES:
        print(f'[{label}] k={len(pinfo)}', flush=True)
        ib_orig = fit_one(dfs, lik, pinfo, 'original')
        if label in CACHE_ONLY:
            ib_var = ib_orig                     # no planning values -> identical model
            print('    variant: identical to original (no planning values)')
        else:
            lik_v = getattr(LKV, lik.__name__)
            ib_var = fit_one(dfs, lik_v, pinfo, 'variant ')
        rows.append(dict(model=label, k=len(pinfo), iBIC_original=round(ib_orig, 1),
                         iBIC_variant=round(ib_var, 1),
                         delta_variant_minus_original=round(ib_var - ib_orig, 1)))
        pd.DataFrame(rows).to_csv(os.path.join(HERE, 'results',
                                  'relinquish_variant_ibic_study2.csv'), index=False)

    out = pd.DataFrame(rows)
    print('\n=== Study 2: iBIC, original vs half-R relinquish variant (lower=better) ===')
    print(out.to_string(index=False))
    best_o = out.loc[out['iBIC_original'].idxmin()]
    best_v = out.loc[out['iBIC_variant'].idxmin()]
    print(f"\nbest original: {best_o['model']} ({best_o['iBIC_original']})")
    print(f"best variant : {best_v['model']} ({best_v['iBIC_variant']})")
    print('saved: results/relinquish_variant_ibic_study2.csv')


if __name__ == '__main__':
    main()
