"""
Replication-based model recovery for the SOFT-GATED model family (Supp Fig S4,
softgate re-basing).

Identical procedure to model_recovery_reps.py (deterministic full-range parameter
grid, common random numbers, per-dataset iBIC winner over REPS datasets), with the
soft-gate rule substituted in BOTH directions:
  * fitting: the 13 candidates use the soft-gated likelihoods of
    study2/mfit_softgate_gen.py (generated by softgate_model_comparison.py:
    second-search counter accrues p1 * b2 per visit, state-tailored first-search
    urns) -- the exact likelihoods of the softgate model comparison (Fig 3A right);
  * generation: recovery_mbmc_sim.simulate_subject is source-patched with the same
    two changes (soft accrual + tailored urns), so every generating model is the
    corresponding soft-gated variant with off-model parameters disabled.
"""
import os
import re
import sys
import time
import argparse
import types
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import multiprocessing as mp

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'study2'))

# scaffold: 60 trials, blocked goal order (20 x depth-3, 20 x depth-2, 20 x depth-1),
# same design as the experiment and recovery_parameter.DEPTH_BLOCKS
SCAFFOLD_PATH = '/tmp/depth_scaffold.npy'
if not os.path.exists(SCAFFOLD_PATH):
    np.save(SCAFFOLD_PATH, np.array([3] * 20 + [2] * 20 + [1] * 20))
SCAFFOLD = np.load(SCAFFOLD_PATH)

import mfit_softgate_gen as LK              # soft-gated likelihoods (study2)
import recovery_common as rc
import recovery_em as REM


def _fast_logsumexp(a, axis=None):
    """Exact drop-in for scipy.special.logsumexp as used by the generated
    likelihoods (real inputs, no weights/keepdims): pairwise logaddexp is the
    same numerically-stable log-sum-exp, computed by a single C ufunc. Verified
    bit-identical on the likelihood outputs; ~15x faster on the (ss, 2) arrays
    used here, where scipy's array-API dispatch dominates the cost."""
    return np.logaddexp.reduce(a, axis=axis)


LK.logsumexp = _fast_logsumexp

# ---- parameter-grid generation machinery (from model_recovery_em.py, which is
# not imported here because its module-level `from cbm import bms` is unavailable
# in this environment; bms is not needed -- winners are decided by iBIC) ---------
PNAMES = ['mb_control', 'discount', 'b1', 'b2', 'mb_cache', 'choice_bias', 'forget',
          'cache_reward', 'cache_plan']
RANGES = {'mb_control': (0.5, 6.0), 'discount': (0.5, 0.98), 'b1': (0.2, 1.0),
          'b2': (0.1, 0.85), 'mb_cache': (0.3, 2.5), 'choice_bias': (-2.2, 2.2),
          'forget': (0.2, 2.5), 'cache_reward': (-1.8, 1.8), 'cache_plan': (0.3, 2.5)}
FIXED_OFF = {'mb_control': 0.0, 'discount': 0.9, 'b1': 0.5, 'b2': 0.3, 'mb_cache': 0.0,
             'choice_bias': 0.0, 'forget': 0.0, 'cache_reward': 0.0, 'cache_plan': 0.0}
FREE = {
    'CB': ['choice_bias'],
    'CCRF': ['mb_cache', 'forget', 'cache_reward'],
    'CCRF_CB': ['mb_cache', 'forget', 'cache_reward', 'choice_bias'],
    'MBMC_optimal': ['mb_control'],
    'MBMC_Depth': ['mb_control', 'discount'],
    'MBMC_Breadth2': ['mb_control', 'b1', 'b2'],
    'MBMC_Breadth1': ['mb_control', 'discount', 'b1'],       # b2 tied to b1
    'MBMC_BD': ['mb_control', 'discount', 'b1', 'b2'],
    'MBMC_CC': ['mb_control', 'discount', 'b1', 'b2', 'mb_cache'],
    'MBMC_CCR': ['mb_control', 'discount', 'b1', 'b2', 'mb_cache', 'cache_reward'],
    'MBMC_CCRF': ['mb_control', 'discount', 'b1', 'b2', 'mb_cache', 'cache_reward', 'forget'],
    'MBMC_CCRF_CB': ['mb_control', 'discount', 'b1', 'b2', 'mb_cache', 'cache_reward',
                     'forget', 'choice_bias'],
    'MBMC_full': ['mb_control', 'discount', 'b1', 'b2', 'mb_cache', 'cache_reward',
                  'forget', 'choice_bias', 'cache_plan'],
}
FIXED_SET = {
    'MBMC_optimal': {'discount': 1.0, 'b1': 1.0, 'b2': 1.0},
    'MBMC_Depth':   {'b1': 1.0, 'b2': 1.0},
    'MBMC_Breadth2': {'discount': 1.0},
}


def gen_params(model, n, rng):
    """Deterministic parameter GRID (identical to model_recovery_em.gen_params)."""
    P = np.zeros((n, len(PNAMES)))
    fixed = dict(FIXED_OFF)
    fixed.update(FIXED_SET.get(model, {}))
    free = FREE[model]
    for k, name in enumerate(PNAMES):
        if name in free:
            grid = np.linspace(*RANGES[name], n)
            rng.shuffle(grid)
            P[:, k] = grid
        else:
            P[:, k] = fixed[name]
    if model == 'MBMC_Breadth1':
        P[:, PNAMES.index('b2')] = 2.0 * P[:, PNAMES.index('b1')]
    return P


def augment(df):
    """Identical to model_recovery_em.augment."""
    df = df.copy()
    df['RT'] = 1.0
    df['choices_numeric'] = df['choice_numeric']
    df = df.sort_values(['sub', 'planning_depth', 'trial_num', 'decision'])
    key = ['sub', 'planning_depth']
    order = (df.drop_duplicates(key + ['trial_num']).sort_values(key + ['trial_num'])
             .assign(_g=lambda x: x.groupby(key).cumcount() + 1))
    df = df.merge(order[key + ['trial_num', '_g']], on=key + ['trial_num'], how='left')
    df['trial_num_within_goal'] = df['_g']
    df = df.drop(columns='_g')
    df['choice_numeric_last'] = (df.groupby(['sub', 'planning_depth', 'decision'])
                                 ['choice_numeric'].shift(1).fillna(0).astype(int))
    return df


def em_fit_serial(sim_dfs, pinfo, lik, ss, maxiter, seed0):
    """Identical to model_recovery_reps.em_fit_serial (hierarchical EM -> iBIC)."""
    N = len(sim_dfs)
    pinfo = [[n, d, list(h)] for (n, d, h) in pinfo]
    bic = 1e18
    best = bic
    for it in range(maxiter):
        old = bic
        results = []
        for i in range(N):
            np.random.seed((seed0 + it * 100003 + i * 7919) % (2 ** 32))
            results.append(rc.process_subject(i, pinfo, sim_dfs, lik, ss))
        for pi in range(len(pinfo)):
            name, dist, _ = pinfo[pi]
            samp = []
            for r in results:
                for item in r[2:]:
                    if item[0] == name:
                        samp += item[3]
            pinfo[pi][2] = REM.refit(dist, samp)
        te = sum(r[1][0] for r in results)
        bic = -2.0 * float(te) + 2 * len(pinfo) * np.log(N * NUM_TRIALS)
        if bic < best:
            best = bic
        if old - bic <= 0:
            break
    return best

# ---- soft-gated generative simulator: source-patch recovery_mbmc_sim -----------
_SIM_OLD = ('            if s2 > 0:\n'
            '                exp2[key] += mb_breadth2\n')
_SIM_NEW = ('            if s2 > 0:\n'
            '                exp2[key] += min(_p_success(s1, tot1, exp1[key]), 1.0)'
            ' * mb_breadth2\n')
_URN_PAIRS = [
    ("(2, 1, 'start'): [2, 8]", "(2, 1, 'start'): [1, 4]"),
    ("(1, 1, 'start'): [4, 8]", "(1, 1, 'start'): [2, 4]"),
    ("(1, 2, 'images/toothbrush.png'): [2, 4]", "(1, 2, 'images/toothbrush.png'): [1, 2]"),
    ("(1, 2, 'images/baby.png'): [2, 4]", "(1, 2, 'images/baby.png'): [1, 2]"),
]


def _build_softgate_sim():
    src = open(os.path.join(HERE, 'recovery_mbmc_sim.py')).read()
    assert src.count(_SIM_OLD) == 1, 'soft-gate sim site not found'
    src = src.replace(_SIM_OLD, _SIM_NEW)
    a = src.index('mb_key = {')
    b = src.index('mb_key2', a)            # patch ONLY the first-search urn dict
    head, block, tail = src[:a], src[a:b], src[b:]
    for old, new in _URN_PAIRS:
        assert block.count(old) == 1, f'urn site not found: {old!r}'
        block = block.replace(old, new)
    mod = types.ModuleType('recovery_mbmc_sim_softgate')
    exec(head + block + tail, mod.__dict__)
    return mod


S = _build_softgate_sim()

# ---- candidate models: soft-gated likelihoods, same 13-model set ---------------
G, B, N = 'gamma', 'beta', 'norm'
_MBB = [['MB_B', G, [1, 1]]]
_MB2 = _MBB + [['MB_depth', B, [1, 1]]]
_MBbd = _MBB + [['MB_depth', B, [1, 1]], ['MB_breadth', B, [1, 1]], ['breadth2', B, [1, 1]]]
_MBc = _MBbd + [['mbcache', G, [1, 1]]]
_MBcr = _MBc + [['cache_reward', N, [0, 5]]]
_MBcrf = _MBcr + [['forget', G, [1, 1]]]
_MBcrfcb = _MBbd + [['mbcache', G, [1, 1]], ['CB', N, [0, 5]], ['forgetC', G, [1, 1]],
                    ['cache_reward', N, [0, 5]]]

CANDIDATES = [
    ('CB',            LK.CacheR_CB_1, [['CB', N, [0, 5]]]),
    ('CCRF',          LK.CacheR_CB_3, [['mbcache', G, [1, 1]], ['forgetC', G, [1, 1]],
                                       ['cache_reward', N, [0, 5]]]),
    ('CCRF_CB',       LK.CacheR_CB_4, [['CB', N, [0, 5]], ['mbcache', G, [1, 1]],
                                       ['forgetC', G, [1, 1]], ['cache_reward', N, [0, 5]]]),
    ('MBMC_optimal',  LK.MB_actionSeparation, _MBB),
    ('MBMC_Depth',    LK.MB_Depth_actionSeparation, _MB2),
    ('MBMC_Breadth2', LK.MB_Breadth_actionSeparation,
                      _MBB + [['MB_breadth', B, [1, 1]], ['breadth2', B, [1, 1]]]),
    ('MBMC_Breadth1', LK.MB_oneBreadth_Depth_actionSeparation,
                      _MBB + [['MB_depth', B, [1, 1]], ['MB_breadth', B, [1, 1]]]),
    ('MBMC_BD',       LK.MB_Breadth_Depth_actionSeparation, _MBbd),
    ('MBMC_CC',       LK.MB_Breadth_Depth_actionSeparation_MBcache1_fullmemory, _MBc),
    ('MBMC_CCR',      LK.MB_Breadth_Depth_actionSeparation_MBcache2_fullmemory, _MBcr),
    ('MBMC_CCRF',     LK.MB_Breadth_Depth_actionSeparation_MBcache2_limitedmemory, _MBcrf),
    ('MBMC_CCRF_CB',  LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting, _MBcrfcb),
    ('MBMC_full',     LK.MB_Breadth_Depth_actionSeparation_MBcache_CB_forgetting_execution,
                      _MBcrfcb + [['cache_plan', G, [1, 1]]]),
]
LABELS = [c[0] for c in CANDIDATES]
NUM_TRIALS = 60

# globals set in main(), inherited by fork workers
N_SUB = 60
REPS = 20
SS = 5000
MAXITER = 20
BASE_SEED = 400


def _simulate_dataset(gen_model, seed):
    truth = gen_params(gen_model, N_SUB, np.random.default_rng(seed))
    rows = []
    for i in range(N_SUB):
        r = S.simulate_subject(truth[i], SCAFFOLD, seed=seed * 100003 + i)
        for d in r:
            d['sub'] = i
        rows.extend(r)
    df = augment(pd.DataFrame(rows))
    return [df[df['sub'] == s].reset_index(drop=True) for s in range(N_SUB)]


def fit_dataset(task):
    """One replication: regenerate dataset, fit all candidates, return winner index."""
    gi, rep = task
    seed = BASE_SEED + gi * 10000 + rep
    dfs = _simulate_dataset(LABELS[gi], seed)
    ibics = np.array([em_fit_serial(dfs, pinfo, lik, SS, MAXITER, seed0=seed * 100 + ci)
                      for ci, (_, lik, pinfo) in enumerate(CANDIDATES)])
    return gi, int(np.argmin(ibics))


def main():
    global N_SUB, REPS, SS, MAXITER
    ap = argparse.ArgumentParser()
    ap.add_argument('--reps', type=int, default=REPS)
    ap.add_argument('--n', type=int, default=N_SUB)
    ap.add_argument('--ss', type=int, default=SS)
    ap.add_argument('--maxiter', type=int, default=MAXITER)
    ap.add_argument('--cores', type=int, default=max(1, (os.cpu_count() or 8) - 1))
    ap.add_argument('--smoke', action='store_true',
                    help='time a single MBMC_full dataset and exit')
    args = ap.parse_args()
    N_SUB, REPS, SS, MAXITER = args.n, args.reps, args.ss, args.maxiter

    if args.smoke:
        t0 = time.time()
        gi, wi = fit_dataset((len(LABELS) - 1, 0))
        print(f'smoke: gen=MBMC_full winner={LABELS[wi]}  '
              f'{time.time()-t0:.0f}s per dataset (ss={SS})', flush=True)
        return

    K = len(LABELS)
    tasks = [(gi, rep) for gi in range(K) for rep in range(REPS)]
    print(f'SOFTGATE recovery: {K} models x {REPS} datasets x {args.n} subj; '
          f'{len(tasks)*K} fits total; ss={SS}, maxiter={MAXITER}, cores={args.cores}',
          flush=True)

    counts = np.zeros((K, K))
    done = np.zeros(K, dtype=int)
    t0 = time.time()
    ctx = mp.get_context('fork')
    with ctx.Pool(args.cores) as pool:
        for gi, wi in pool.imap_unordered(fit_dataset, tasks):
            counts[gi, wi] += 1
            done[gi] += 1
            if done.sum() % 26 == 0:
                print(f'  {done.sum()}/{len(tasks)} datasets fit '
                      f'({time.time()-t0:.0f}s)', flush=True)
    conf = counts / REPS

    pd.DataFrame(conf, index=LABELS, columns=LABELS).to_csv(
        os.path.join(HERE, 'results', 'model_recovery_softgate_reps_confusion.csv'))
    print('\nProportion of %d datasets won by each model (rows=generating):' % REPS)
    print(pd.DataFrame(conf, index=LABELS, columns=LABELS).round(2).to_string())
    diag = np.diag(conf)
    print('\ndiagonal (self-recovery):', dict(zip(LABELS, np.round(diag, 2))))

    sns.set(style='white', font_scale=1.15)
    plt.figure(figsize=(9.5, 8))
    ax = sns.heatmap(conf, annot=True, fmt='.2f', cmap='viridis', vmin=0, vmax=1,
                     square=True, linewidths=0.5, xticklabels=LABELS, yticklabels=LABELS,
                     cbar_kws={'label': 'proportion of %d datasets won (iBIC)' % REPS,
                               'shrink': 0.8})
    ax.set_xlabel('Recovered (winning) model'); ax.set_ylabel('Generating model')
    ax.tick_params(axis='x', rotation=40); plt.setp(ax.get_xticklabels(), ha='right')
    ax.tick_params(axis='y', rotation=0)
    plt.title('Model recovery, soft-gated models: iBIC-winner proportion over '
              '%d datasets (N=%d each)' % (REPS, args.n))
    plt.tight_layout()
    plt.savefig(os.path.join(HERE, 'model_recovery_softgate_reps_study2.png'), dpi=300,
                bbox_inches='tight')
    plt.close()
    print(f'\nTotal {time.time()-t0:.0f}s. Saved: model_recovery_softgate_reps_study2.png, '
          'results/model_recovery_softgate_reps_confusion.csv')
    print('SOFTGATE MODEL RECOVERY DONE', flush=True)


if __name__ == '__main__':
    main()
